tap homebrew/homebrew-php
install ansible
install bash
install cabextract
install cmake
install composer
install cscope
install ctags
install editorconfig
install freetype
install gdbm
install gettext
install git
install git-flow-avh
install gnu-getopt
install icu4c
install jpeg
install libpng
install libtool
install libxml2
install libyaml
install nmap
install node
install openssl
install openssl@1.1
install p7zip
install pcre
install perl
install php-cs-fixer
install php71
install python
install readline
install rmtrash
install ruby
install sqlite
install the_silver_searcher
install tree
install unixodbc
install unrar
install vim
install xz
install yarn
install zsh
