tap "ggpeti/rmrec"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "universal-ctags/universal-ctags"
brew "automake"
brew "node", link: false
brew "bower"
brew "gettext"
brew "pcre"
brew "cairo"
brew "cmake"
brew "composer"
brew "ffmpeg"
brew "git"
brew "git-flow-avh"
brew "grunt-cli"
brew "irssi"
brew "node@10", link: true
brew "pkg-config"
brew "python@2"
brew "rename"
brew "rmtrash"
brew "rsync"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "koekeishiya/formulae/chunkwm"
brew "koekeishiya/formulae/skhd"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
